export const tradeItems = [
  {
    name: 'Normal Purity Fist',
    refs: '20',
    keys: '57',
    imageUrl: 'img/giveaway-img-4.png',
    desc: '',
  },
  {
    name: `Circling Peace Sign Doctor's Sack`,
    refs: '250',
    keys: '4',
    imageUrl: 'img/giveaway-img-1.png',
    desc: '',
  },
  {
    name: 'Scorching Flames Kiss King',
    refs: '127',
    keys: '07',
    imageUrl: 'img/giveaway-img-2.png',
    desc: '',
  },
  {
    name: `Searing Plasma Bloke's Bucket Hat`,
    refs: '567',
    keys: '234',
    imageUrl: 'img/giveaway-img-3.png',
    desc: '',
  },
  {
    name: 'Strange Festive Sandvich',
    refs: '41',
    keys: '56',
    imageUrl: 'img/giveaway-img-4.png',
    desc: '',
  },
  {
    name: 'Strange Professional Killstreak Australium ',
    refs: '143',
    keys: '247',
    imageUrl: 'img/item-img-1.png',
    desc: '',
  },
  {
    name: 'Green Energy Airdog',
    refs: '78',
    keys: '798',
    imageUrl: 'img/item-img-2.png',
    desc: '',
  },
  {
    name: 'Burning Flames Nasty Norsemann',
    refs: '23',
    keys: '31',
    imageUrl: 'img/item-img-3.png',
    desc: '',
  },
  {
    name: 'Aces High Deep Cover Operator',
    refs: '108',
    keys: '287',
    imageUrl: 'img/item-img-4.png',
    desc: '',
  },
  {
    name: 'Miami Nights Towering Titanium Pillar of Hats',
    refs: '202',
    keys: '95',
    imageUrl: 'img/item-img-5.png',
    desc: '',
  },
  {
    name: 'Circling Peace Sign Mann of Reason',
    refs: '969',
    keys: '596',
    imageUrl: 'img/item-img-6.png',
    desc: '',
  },
  {
    name: 'Tesla Coil Wing Mann',
    refs: '805',
    keys: '8',
    imageUrl: 'img/item-img-7.png',
    desc: '',
  },
  {
    name: 'Starstorm Insomnia Nasty Norsemann',
    refs: '947',
    keys: '358',
    imageUrl: 'img/item-img-6.png',
    desc: '',
  },
  {
    name: 'Kill-a-Watt Harmburg',
    refs: '86',
    keys: '467',
    imageUrl: 'img/trade-img-1.png',
    desc: '',
  },
  {
    name: 'Purple Confetti Sky High Fly Guy',
    refs: '85',
    keys: '78',
    imageUrl: 'img/trade-img-2.png',
    desc: '',
  },
  {
    name: 'Burning Flames Kiss King',
    refs: '56',
    keys: '96',
    imageUrl: 'img/trade-img-3.png',
    desc: '',
  },
];
